# Generated by Django 3.2.6 on 2021-08-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_followup_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='handle_upload_follow_ups/'),
        ),
    ]
